server:
  port: 8080
spring:
  application:
    name: editUpload
  thymeleaf:
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    content-type: text/html
    encoding: utf-8
  messages: messages_zh_CN

